### ISSUE TITLE
Incompatable with carpet mod

### ISSUE THREAD

**Issue by Vexxen1** [Fusion-Flux/GravityChanger#24]
This mod is incompatable with carpet mod

**Comment by Fusion-Flux** [comment]
yeah

**Comment by Vexxen1** [comment]
and its detrimental too my project, so i was hoping for a fix

**Comment by TriibuNupsik** [comment]
Is there going to be a fix for the incompatibility whit the carpet mod?

**Comment by kristibektashi** [comment]
This is still an issue

**Comment by Fusion-Flux** [comment]
fixed
