### ISSUE TITLE
Mod acts very strange when optifine is enabled.

### ISSUE THREAD

**Issue by XDCam15** [Fusion-Flux/GravityChanger#28]
First off, really love this mod. But, there is an issue with the mod when optifine is involved.

When optifine is used, the camera orientation goes all over the place when I switch the gravity to anything else but down. Plus, the controls go all wacky and it's extremely difficult to control the game with this issue. Without optifine, the mod works perfectly fine so I don't know why optifine messes with the camera and controls.

Is there a way to make this mod compatible with optifine so this issue could be resolved? I would really appreciate it. Keep up the good work btw!

**Comment by Fusion-Flux** [comment]
Optifabric support isn't planned.
Though this mod is confirmed to work with Sodium + Iris so id recommend using that instead.
