### ISSUE TITLE
Minecraft Crashing when having this mod

### ISSUE THREAD

**Issue by Tomergngn** [Fusion-Flux/GravityChanger#38]
I've been using gravity API for a long time now, when it was called gravity changer.
I tried launching the 1.19 version of the mod in CurseForge, and a few things happened:
1. I didn't see the mod in the CurseForge "Installed Mods" menu
2. when I launched it, minecraft crashed immediately giving me crash error 1

Thanks in advance, Tom

**Comment by ImSpaceLover** [comment]
This mod isn't on curseforge, use modrinth

**Comment by Tomergngn** [comment]
I'm not talking about the website, I'm talking about CurseForge the application (mod launcher).
It isn't a problem with the app however, because I used CurseForge many times before and it launched perfect every time for years.
