### ISSUE TITLE
[INCOMPATIBILITY] Avoid function override

### ISSUE THREAD

**Issue by charlyb01** [Fusion-Flux/GravityChanger#39]
Hello,

Somebody told me there was an incompatibility issue with my mod [XP Storage](https://github.com/sf-inc/xp_storage/issues/20).
I checked both our codes and it seems the issue comes from your side. Indeed, I'm injecting in Minecraft code (modifying a variable actually) but you're overriding the associated function.
Experience Bottles already override the `use` function so you shouldn't [override](https://github.com/Fusion-Flux/Gravity-Api/blob/1.19/src/main/java/com/fusionflux/gravity_api/mixin/ExperienceBottleItemMixin.java) it to avoid incompatibilities. Instead, you should try injections. I didn't really check why you override it, but it's sure you can do this. You could inject at head with cancel option for example, or if you can do better, do it because the first option is not really amazing. If you want me to check what else you could do, just tell me, I didn't take time yet.

**Comment by Fusion-Flux** [comment]
fixed
