### ISSUE TITLE
[Suggestion] Immersive Portals Compatibility

### ISSUE THREAD

**Issue by The-Nyla** [Fusion-Flux/GravityChanger#4]
Integration with immersive portal so if for example you go into a portal, and the exit portal is facing down, your gravity will change. 

Idk how to explain this well so I just made a basic drawing of how it would work

![portal-compat](https://user-images.githubusercontent.com/79489385/170594165-d3c364e7-509b-470f-a3ed-f9e02c01a645.png)

**Comment by espot07** [comment]
Didn't not only the original mod but Qouteall's fork of the mod already have Immersive Portals compatibility built-in? Even then Qouteall is literally the CREATOR of Immersive Portals and has settings within Immersive Portals that work directly with the Gravity Changer mod. So unless the creator of this fork deliberately removed compatibility, it is most likely compatible with Immersive Portals.
Edit: So, unless I'm doing something really wrong, I can't even load into a world with Immersive Portals and this mod on. Here's my crash report: https://pastebin.com/eD3xBqrw

**Comment by ImSpaceLover** [comment]
Making this mod compatible with Immersive Portals is what qouteall have to do. Developer of this mod can't do anything unless they change Immersive Portals code
