### ISSUE TITLE
[QUESTION] Fabric version vs Quilt version

### ISSUE THREAD

**Issue by Endninja137** [Fusion-Flux/GravityChanger#46]
As of writing this, the 2 newest versions of this mod (v0.7.19 and v0.7.20) are marked as Quilt mods, and the rest are for Fabric. Are there any differences between the latest Fabric and Quilt versions?

**Comment by Fusion-Flux** [comment]
not at the moment but once im done the quilt version will have tons of new content + tons of new blocks + props

**Comment by Fusion-Flux** [comment]
none lol but i want to switch over to quilt if possible
