### ISSUE TITLE
Old (crashing) version featured on Modrinth

### ISSUE THREAD

**Issue by MightyKnight** [Fusion-Flux/GravityChanger#47]
The 0.7.19 version that crashes on world loading is featured on Modrinth instead of 0.7.20.
Most of the times nobody looks into the versions tab but just downloads from the sidebar, so this might be a big issue because the mod looks broken.

![grafik](https://user-images.githubusercontent.com/38622942/198902411-ae45b6c6-7748-424d-8050-e2aef9109ca9.png)

**Comment by Fusion-Flux** [comment]
fixed
