### ISSUE TITLE
Incompatibility with CameraUtils

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [Fusion-Flux/GravityChanger#48]
![image](https://user-images.githubusercontent.com/98014624/200114741-fcb4fe63-2006-4013-8f6d-1811f0078ab1.png)

**Comment by Fusion-Flux** [comment]
overall this is just meaning we need to fix all the mixins in the mod

**Comment by leo60228** [comment]
CameraUtils fixed this on their end.

**Comment by Fusion-Flux** [comment]
oh based
