### ISSUE TITLE
Crash with Automobility Quilt [1.19.2]

### ISSUE THREAD

**Issue by waddon1** [Fusion-Flux/GravityChanger#49]
I initially reported this to Automobility, but was told to report to Gravity API instead. This crash occurs when using an automobility vehicle and then the world crashes every time on startup after the initial crash.

https://pastebin.com/T3nVb6pN

**Comment by leo60228** [comment]
This is an issue with Paradise Lost, not Gravity API: https://github.com/devs-immortal/Paradise-Lost/blob/0.2.0/1.19/master/src/main/java/net/id/paradiselost/mixin/entity/LivingEntityMixin.java#L65
