### ISSUE TITLE
Head Rotations and position when changing gravity look weird with the firstpersonmodel mod installed

### ISSUE THREAD

**Issue by The-Nyla** [Fusion-Flux/GravityChanger#6]
![2022-06-18_14 18 09](https://user-images.githubusercontent.com/79489385/174451572-a4927adb-3ea2-42d7-8060-950947e52ffd.png)
![2022-06-18_14 17 43](https://user-images.githubusercontent.com/79489385/174451574-22f47f09-11c1-428a-90ab-5dad7ef1a42a.png)

**Comment by maximumpower55** [comment]
This isn't fixable on gravity api's side due to how FirstPersonModel works but they might be able to fix it
