### ISSUE TITLE
Awkward

### ISSUE THREAD

**Issue by CyborgCabbage** [Fusion-Flux/GravityChanger#8]
Sooo I've been developing my own fork of GravityChanger, still a lot of work that needs doin but it is getting there. Also a mod that depends on it
(CyborgCabbage/amethystgravity), with gravity plating and field generators and that sort of stuff. 
Of course, it would be confusing and unhelpful to players if there were two incompatible, nearly identical versions of the same mod. 
Not sure how to go about this, whether I should merge my changes into your fork or the other way around.

Here are the main things I've changed in my version:
* Changing gravity direction from the client-side is now supported, this is required for the gravity plating to work properly.
* API changed so that there are now "gravity sources" with different priorities
* Smooth camera rotation in first and third person
* API now has Boolean rotateVelocity and rotateView, these are again needed for the gravity plates

**Comment by Fusion-Flux** [comment]
uhuhuhuh heres an invite to my discord so we can discuss better
https://discord.gg/ffwZ8NMh4A

**Comment by ImSpaceLover** [comment]
I think this issue can be closed as resolved now?
